export const ericisms = [
    "Twin Nuclei",
    "Agentic",
    "Audience Capture",
    "Anti-Interesting",
    "The Big Nap",
    "Chess-Opening Problem",
    "Critical Feeling",
    "Degraded State",
    "Edugenic Harm",
    "Embedded Growth Obligations (EGOs)",
    "Extractive Elite",
    "Fact-Checker",
    "Facultative Autism",
    "Gated Institutional Narrative (GIN)",
    "Genius vs Excellence",
    "Goliaputian",
    "Hypocrisy Budget",
    "Iago Media",
    "Ideological Dining a la Carte",
    "Injustice Budget",
    "Institutional Betrayal",
    "Kayfabrication",
    "The Least Interesting, Interesting Thing",
    "Load-Bearing Fictions",
    "Long-Form Podcasting",
    "Limbic Business Model",
    "The Looting Party",
    "Long Term vs Short Term Optimization",
    "Map the Silences",
    "Macropaternalism",
    "New Orchards",
    "No-Pill",
    "Perfectly Legal",
    "Reputational Violence",
    "Responsible Conspiracy Theorizing",
    "Semi-reliable Communal Sense-making",
    "Snap-to-Grid Intellectualism",
    "Streisand Squeeze",
    "Teaching Disabilities",
    "Truth, Meaning, Fitness, Grace",
    "Umwelt Hacking",
    "Universal Basic Forgiveness",
    "The United States of Absolutely Nothing (U.S.A.N.)",
    "White Suit",
]

export const thingyTerms = [
    "consciousness",
    "fractals",
    "game of life",
    "qualia",
    "Riemann zeta",
    "calculus",
    "settled science",
    "consensus",
    "Gödel's incompleteness theorem",
    "peer review",
    "decentralization",
    "DAO",
    "Dunbar's number",
    "my ToE is in an Excel spreadsheet",
    "Golden ratio",
    "Fibonacci sequence",
    "intellectual",
    "Doctors recommend (counterpoint: big tobacco)",
    "Tone policing (calm down and try to be more polite)",
    "Sacred Geometry",
    "Electric Universe",
    "Language (physics, analogies)",
    "Prototype Thruster (with new “physics”)",
    "Unruh",
]